# Prometheus Configuration - Imam Abdul Fatah
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'wine_quality_inference'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:5000']
