version: '3.8'

services:
  inference-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wine_quality_inference
    ports:
      - "5000:5000"
    restart: always
    environment:
      - PORT=5000

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: wine_quality_prometheus
    volumes:
      - ./2.prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.0.0
    container_name: wine_quality_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    depends_on:
      - prometheus
